//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.06 at 06:07:47 PM IST 
//


package org.wso2.custom.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wso2.carbon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wso2.carbon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Automation }
     * 
     */
    public Automation createAutomation() {
        return new Automation();
    }

    /**
     * Create an instance of {@link Automation.Role }
     * 
     */
    public Automation.Role createAutomationRole() {
        return new Automation.Role();
    }

    /**
     * Create an instance of {@link Automation.Role.User }
     * 
     */
    public Automation.Role.User createAutomationRoleUser() {
        return new Automation.Role.User();
    }

    /**
     * Create an instance of {@link Automation.Role.Permission }
     * 
     */
    public Automation.Role.Permission createAutomationRolePermission() {
        return new Automation.Role.Permission();
    }

}
